"""init

Revision ID: 01ac641e7e53
Revises: 
Create Date: 2025-08-08 17:25:39.291369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ac641e7e53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('your_table_name')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('create_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('directly_rel')
        batch_op.drop_column('industry_dept')
        batch_op.drop_column('industry_area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_area', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('industry_dept', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('directly_rel', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.VARCHAR(length=50), nullable=True))

    op.create_table('your_table_name',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('create_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('sys_org_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('com_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('district', sa.VARCHAR(length=32), nullable=True),
    sa.Column('street', sa.VARCHAR(length=256), nullable=True),
    sa.Column('industry_area', sa.VARCHAR(length=256), nullable=True),
    sa.Column('industry_dept', sa.VARCHAR(length=256), nullable=True),
    sa.Column('size', sa.VARCHAR(length=32), nullable=True),
    sa.Column('type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('directly_rel', sa.VARCHAR(length=32), nullable=True),
    sa.Column('address', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('credit_code', sa.VARCHAR(length=32), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
